name: reconstruction_3d
description: "3D Reconstruction interface app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  video_player: ^2.8.6 
  image: ^4.1.7
  sqflite: ^2.3.3+1
  path: ^1.9.0
  share_plus: ^9.0.0
  flutter_secure_storage: ^9.0.0
  model_viewer_plus: ^1.7.2
  screenshot: ^2.3.0
  path_provider: ^2.1.3
  dartssh2: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bowl_asset.glb
    - lib/assets/bowl_asset.jpg
    - lib/assets/orange_asset.glb
    - lib/assets/orange_asset.jpg
    - lib/assets/teddybear_asset.glb
    - lib/assets/teddybear_asset.jpg
